
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import { unkempt } from "./fonts";
import Navbar from "../components/NavBbar";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
import NextAuthProvider from "./NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

export default function RootLayout({
  children,
}: LayoutProps) {
  return (
      <html lang="en">
        <body className={[inter.className].join(' ')}>
          <NextAuthProvider>
            
          <Navbar></Navbar> 
          <main className="min-h-screen"> 
            {children}
          </main>
          <Footer></Footer>

          </NextAuthProvider>
        </body>
      </html> 
  );
}
